name: CI/CD

on:
  push:
    branches: ["main"]

env:
  REGISTRY: registry.digitalocean.com/ollama-go-gpt
  IMAGE_NAME: my-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_PASSWORD }}

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set image for deployment
        run: echo "IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'

      # - name: Configure kubeconfig
      #   run: doctl kubernetes cluster kubeconfig save ${{ secrets.DOKS_CLUSTER }}

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl set image deployment/ollama-backend ollama-backend=${IMAGE} -n ${{ secrets.K8S_NAMESPACE }}
      #     kubectl rollout status deployment/ollama-backend -n ${{ secrets.K8S_NAMESPACE }}